### ISSUE TITLE
AWS CredentialsProviderError

### ISSUE THREAD

**Issue by lpbonomi** [SoftwareBrothers/adminjs-upload#69]
When trying to define a `File` resource I get the following error:

```
CredentialsProviderError: Could not load credentials from any providers
    at /Users/luispe/Repos/ultradrop-app/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /Users/luispe/Repos/ultradrop-app/node_modules/@smithy/property-provider/dist-cjs/chain.js:11:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/Users/luispe/Repos/ultradrop-app/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async SignatureV4.credentialProvider (/Users/luispe/Repos/ultradrop-app/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.presign (/Users/luispe/Repos/ultradrop-app/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:29:29)
    at async /Users/luispe/Repos/ultradrop-app/node_modules/@aws-sdk/s3-request-presigner/dist-cjs/getSignedUrl.js:32:27
    at async /Users/luispe/Repos/ultradrop-app/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/luispe/Repos/ultradrop-app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /Users/luispe/Repos/ultradrop-app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async getSignedUrl (/Users/luispe/Repos/ultradrop-app/node_modules/@aws-sdk/s3-request-presigner/dist-cjs/getSignedUrl.js:54:24)
    at async fillRecordWithPath (file:///Users/luispe/Repos/ultradrop-app/node_modules/@adminjs/upload/build/features/upload-file/utils/fill-record-with-path.js:11:20)
    at async fillPath (file:///Users/luispe/Repos/ultradrop-app/node_modules/@adminjs/upload/build/features/upload-file/upload-file.feature.js:37:21)
    at async file:///Users/luispe/Repos/ultradrop-app/node_modules/@adminjs/express/lib/buildRouter.js:24:22
```

This is my code:

```
export const createFileResource = (componentLoader: ComponentLoader) => ({
  resource: {
    id: "id",
    model: getModelByName("File"),
    client: prisma,
  },
  features: [
    uploadFeature({
      componentLoader,
      provider: {
        aws: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_ACCESS_SECRET,
          region: process.env.AWS_REGION,
          bucket: process.env.AWS_BUCKET,
        },
      },
      properties: {
        key: "key",
        mimeType: "mime",
      },
    }),
  ],
});
```

I've even tried hardcoding my credentials, but it still didn't work

**Comment by lpbonomi** [comment]
Looks that I had to configure the credentials with the CLI using aws configure

**Comment by giteshraheja** [comment]
@lpbonomi what happens on server where aws CLI is not available?

**Comment by lpbonomi** [comment]
I'm sorry, but I don't have access to that project anymore
